#!/usr/bin/bash

# list devices, write file path
device=$(bt-device -l | tail -n +2 | fzf)
if [ -z "$device" ]
then
  exit
else
device_mac=$(echo $device | rev |  cut -d "(" -f 1 | rev | cut -d\) -f1)
bt-device --set $device_mac Trusted 1
bt-obex -p $device_mac $(cd $PWD && fzf)
fi
