#!/usr/bin/env bash

DEFAULT_BASE_DIRS=("$HOME" "/etc")
# base_dir=$DEFAULT_BASE_DIRS

# [ ! -z "$1" ] && base_dir=$1
for dir in ${DEFAULT_BASE_DIRS[@]}
do

repos=$(fd --ignore-file $HOME/.config/dgit/ignore -a --base-directory $dir -H -I -t d -0 "\.git$" -x  echo {//})

while IFS= read -r repo && [ ! -z "$repos" ]; do
  status=$(git -C $repo status --porcelain 2>/dev/null | cut -c2 | uniq | xargs)
  push_status=$(git -C $repo diff @{u})
  status2=""
  [ ! -z "$push_status" ] && status2="⇡"
  [ ! -z "$status" ] || [ ! -z "$status2" ] && echo -e "$repo \t  [ $status $status2 ]"
done <<< "$repos"

done
