#!/usr/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
--radius=200  \
\
--pass-media-keys \
--pass-screen-keys \
--pass-volume-keys \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--blur 8              \
--clock               \
--indicator           \
--time-str="%I:%M:%S %p"  \
--date-str="%A, %d %m %Y" \
--keylayout 1         \
\
--verif-text="Drinking verification can..."  \
--wrong-text="YOU IDIOT!, Fuck off" \

# --screen 1            \

