#!/usr/bin/sh
# i3lock -i ~/.config/lockimage.png -t
#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
--radius=200  \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 8              \
--clock               \
--indicator           \
--timestr="%I:%M:%S %p"  \
--datestr="%A, %d %m %Y" \
--keylayout 1         \
\
--veriftext="Drinking verification can..."  \
--wrongtext="YOU IDIOT!, Fuck off" \
--show-failed-attempts
